# Generated by Django 6.1.1 on 2026-10-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_status',
            field=models.CharField(choices=[('NONE', 'Sin solicitud'), ('REQUESTED', 'Solicitud pendiente'), ('REJECTED', 'Solicitud rechazada')], default='NONE', max_length=20),
        ),
    ]
