# Generated by Django 6.1.1 on 2026-10-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_order_cancellation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancellation_status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cancellation_status',
            field=models.CharField(choices=[('NONE', 'Sin solicitud'), ('REQUESTED', 'Solicitud pendiente'), ('REJECTED', 'Solicitud rechazada'), ('APPROVED', 'Cancelado')], default='NONE', max_length=20),
        ),
    ]
