# Generated by Django 6.1 on 2026-08-21 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clase', models.CharField(max_length=100, verbose_name='Nombre de la Clase')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.IntegerField(primary_key=True, serialize=False, verbose_name='Número de Estudiante')),
                ('titulo', models.CharField(max_length=20, verbose_name='Título/Tratamiento')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id_salon', models.IntegerField(primary_key=True, serialize=False, verbose_name='Número de Salón')),
            ],
            options={
                'verbose_name': 'Salón',
                'verbose_name_plural': 'Salones',
            },
        ),
        migrations.CreateModel(
            name='EstudianteClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.clase')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante')),
            ],
            options={
                'verbose_name': 'Inscripción de Clase',
                'verbose_name_plural': 'Inscripciones de Clases',
                'unique_together': {('estudiante', 'clase')},
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='clases',
            field=models.ManyToManyField(related_name='estudiantes', through='estudiantes.EstudianteClase', to='estudiantes.clase', verbose_name='Clases Inscritas'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='estudiantes.salon', verbose_name='Salón Asignado'),
        ),
    ]
