# Generated by Django 6.1 on 2026-08-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='id_estudiante',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Número de Estudiante'),
        ),
    ]
