# Generated by Django 6.1.1 on 2026-09-24 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('rol', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=50)),
                ('usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('codigo_postal', models.CharField(max_length=20)),
                ('sucursal', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(max_length=50)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'direccion',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.BigAutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
    ]
