# Generated by Django 6.1.1 on 2026-10-01 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del área de conocimiento', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción opcional del área')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del curso o bootcamp', max_length=200)),
                ('description', models.TextField(help_text='Descripción detallada del curso')),
                ('instructor', models.CharField(blank=True, help_text='Nombre del instructor (estilo Udemy)', max_length=200)),
                ('enrollment_cost', models.DecimalField(decimal_places=2, help_text='Costo de matrícula', max_digits=10)),
                ('start_date', models.DateField(help_text='Fecha de inicio')),
                ('end_date', models.DateField(help_text='Fecha de término')),
                ('max_capacity', models.PositiveIntegerField(help_text='Límite máximo de cupos por cohorte')),
                ('available_capacity', models.PositiveIntegerField(help_text='Cupos actualmente disponibles')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.area')),
            ],
        ),
    ]
