# Generated by Django 6.1.1 on 2026-10-02 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_instructor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'role': 'INSTRUCTOR'}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cursos_impartidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
