# Generated by Django 6.1 on 2026-08-27 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('CodAutor', models.AutoField(primary_key=True, serialize=False)),
                ('NombreAutor', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('CodEditorial', models.AutoField(primary_key=True, serialize=False)),
                ('NombreEditorial', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('CodLector', models.AutoField(primary_key=True, serialize=False)),
                ('ApellidoP', models.CharField(max_length=100)),
                ('ApellidoM', models.CharField(max_length=100)),
                ('Nombres', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('CodLibro', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Libro_Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodAutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.autor')),
                ('CodLibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.libro')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('CodLibro', 'CodAutor'), name='unique_libro_autor')],
            },
        ),
        migrations.CreateModel(
            name='Libro_Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodEditorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.editorial')),
                ('CodLibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.libro')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('CodLibro', 'CodEditorial'), name='unique_libro_editorial')],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaDev', models.DateField()),
                ('CodLector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lector')),
                ('CodLibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.libro')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('CodLibro', 'CodLector'), name='unique_prestamo_libro_lector')],
            },
        ),
    ]
